import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import axios from 'axios'
import { CardType } from './types/cardTypes'

export default function Home () {
  const baseURL = 'http://localhost:3000'
  const [loading, setLoading] = useState<boolean>(false)
  const [cards, setCards] = useState<CardType[]>([])
  const [value, setValue] = useState<string>('')

  const getData = async () => {
    setLoading(true)
    const response = await axios.get(`${baseURL}/api/hello`, {
      params: {
        name: value
      }
    })
    console.log(response)
    if (response.status !== 200) {
      alert(`you suck!, ${response.statusText}`)
    } else {
      const card: CardType = response?.data
      setCards([...cards, card])
    }
    setLoading(false)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to MY TEST</h1>
        <section id='input-section'>
          <form
            className={styles.submitForm}
            id='card-form'
            onSubmit={e => {
              e.preventDefault()
              getData()
            }}
          >
            <input
              disabled={loading}
              value={value}
              onChange={e => setValue(e.target.value)}
            />
            <button disabled={loading}>Do the thing</button>
          </form>
        </section>

        <section id='cards-section'>
          {cards.map((card, i) => (
            <div className='card' key={i}>
              <img src={card.imageUrl} />
              <h1>{card.name}</h1>
            </div>
          ))}
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
